{% set name = "openspecfun" %}
{% set version = "0.5.4" %}
{% set sha256 = "b65725c5d3926688aeb262d1a0b332114734f5193c2a80a41e6e53f5465220ee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openspecfun/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-no-cc-override.patch
    - 0002-no-fc-override.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - openlibm 0.5.4

  run:
    - openlibm 0.5.4

test:
  commands:
    - test -f "${PREFIX}/include/Faddeeva.h"                             # [unix]
    - test -f "${PREFIX}/lib/libopenspecfun.a"                           # [unix]
    - test -f "${PREFIX}/lib/libopenspecfun${SHLIB_EXT}"                 # [unix]


about:
  home: https://github.com/JuliaLang/openspecfun
  license: MIT, Public Domain
  license_file: LICENSE.md
  summary: A collection of special mathematical functions
  dev_url: https://github.com/JuliaLang/openspecfun

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
    - SylvainCorlay
